[package]
name = "groom"
description = "A command line utility for processing mustache templates written in rust"
version = "0.1.0"
authors = ["Christopher Field <cfield2@gmail.com>"]
license = "GPL-3.0"
readme = "README.md"
keywords = ["cli", "mustache", "template"]
categories = ["command-line-utilities", "text-processing"]
homepage = "https://github.com/volks73/groom"
repository = "https://github.com/volks73/groom"

[[bin]]
name = "groom"
path = "src/main.rs"

[dependencies]
ansi_term = "0.10"
atty = "0.2"
clap = "2.27"
log = "0.3"
loggerv = "0.6"
mustache = { git = "https://github.com/volks73/rust-mustache.git" }
serde = "1.0"
serde_yaml = "0.7"

